[package]
name = "chatwise-father"
version = "0.2.10"
edition = "2021"

[dependencies]
object = "0.36"
memmap2 = "0.9"
brotli = "7.0"
glob = "0.3"
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
regex = "1.11"
